spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  security:
    user:
      name:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  session:
    jdbc:
      initialize-schema: always
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: ${JWT}
  expiration-ms: 86400000

cloudinary:
  cloud-name: ${CLOUD-NAME}
  api-key: ${API-KEY}
  api-secret: ${API-SECRET}
server:
  port: 8080
google:
  client-id: ${GOOGLE_CLIENT_ID}
app:
  front-base-url: ${FRONT_BASE_URL:http://localhost:5173}
newsletter:
  cron: "0 0 0 L * *"