spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  session:
    jdbc:
      initialize-schema: always
  output:
    ansi:
      enabled: ALWAYS

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true